/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PostTest3;

/**
 *
 * @author RizkyKiwa
 */
public class tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form latihanborderlayout
     */
    public tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtengah = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        visimisi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        informasi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        tentang = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        wisata = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jatas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jbawah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtengah.setBackground(new java.awt.Color(255, 204, 204));
        jtengah.setPreferredSize(new java.awt.Dimension(560, 300));
        jtengah.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 102));

        jLabel15.setFont(new java.awt.Font("Snap ITC", 0, 18)); // NOI18N
        jLabel15.setText("Sistem Informasi Kota Tarakan");

        jLabel16.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel16.setText("Selamat Datang di ");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Kota Tarakan adalah sebuah kota yang terletak di sebelah utara Kalimantan, kota ini sangat dekat dengan perbatasan antara Indonesia dan Malaysia. Sehingga tidak heran apabila banyak produk-produk industri dari Malaysia yang masuk ke Tarakan atau dijual di Tarakan.\n\nSebagai sebuah kota yang terletak di ujung utara Kalimantan Indonesia, Kota Tarakan ternyata menyimpan banyak potensi wisata yang menarik. Seperti halnya beberapa kota di Kalimantan, Kota Tarakan juga memiliki sejarah panjang mulai dari kerajaan yang pernah berdiri di sana serta sejarah pendaratan tentara penjajah seperti Belanda dan Jepang.\n\nKota Tarakan merupakan kota terkaya ke-17 di Indonesia. Kota ini memiliki ladang minyak serta tambang yang besar, hal ini pulalah yang membuat Belanda dan Jepang mendarat di Kota Tarakan.\n");
        jScrollPane3.setViewportView(jTextArea2);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\RizkyKiwa\\Documents\\NetBeansProjects\\VISUAL_B_1515015055_160497\\src\\PostTest3\\mangrove-forest-tarakan.jpg")); // NOI18N

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel16))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17))
                            .addComponent(jLabel15))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE))
        );

        jtengah.add(home, "card2");

        visimisi.setBackground(new java.awt.Color(102, 255, 51));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 255, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("VISI :.\n\nMewujudkan Tarakan sebagai kota perdagangan, jasa, industri, perikanan dan pariwisata, \ndidukung oleh sumber daya manusia serta infrastruktur yang handal dan berwawasan lingkungan \n \n\n.: MISI :.\n\nMelaksanakan pengembangan dan pembangunan kawasan perdagangan, industry, perikanan dan pariwisata.\nMeningkatkan dan mengembang kualitas sumberdaya manusia.\nMelaksanakan peningkatan, pembangunan dan pengembangan infrastruktur.\nMelaksanakan pengembangan dan pembangunan lingkungan hidup.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout visimisiLayout = new javax.swing.GroupLayout(visimisi);
        visimisi.setLayout(visimisiLayout);
        visimisiLayout.setHorizontalGroup(
            visimisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );
        visimisiLayout.setVerticalGroup(
            visimisiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1148, Short.MAX_VALUE)
        );

        jtengah.add(visimisi, "card3");

        informasi.setBackground(new java.awt.Color(0, 0, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Informasi Kota Tarakan");

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(0, 0, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Tarakan,- Dibangunnya Museum Perminyakan Kota Tarakan diyakini kedepan akan menjadi salah satu ikon kebanggaan masyarakat Tarakan, karena keberadaannya tidak dapat dipungkiri menjadi acuan atau referensi sejarah perminyakan Indonesia, dimana nama Tarakan sudah terlibat dalam transaksi perdagangan minyak dunia sejak era Perang Dunia II (Belanda/ NICA menjajah Indonesia).\n\nHal tersebut diungkapkan Walikota Tarakan, Sofian Raga, saat bersama Ketua DPRD Kota Tarakan Sabar Santoso memenuhi undangan PT Pertamina untuk meninjau benda – benda sejarah yang akan disumbangkan sebagai bahan koleksi museum.\n\n“Atas nama pemerintah kota dan seluruh masyarakat kota Tarakan, kami memberikan apresiasi yang sebesar – besarnya atas dukungan yang diberikan oleh semua pihak,” ujar Sofian Raga beberapa waktu lalu, Jumat (17/02).\n\nMuseum Perminyakan kota Tarakan diproyeksikan menjadi salah satu Wahana Edutaiment, khususnya bagi warga Tarakan dan Kalimantan Utara, serta bagi wisatawan domestik dan internasional yang ingin mengenal lebih jauh/ tertarik terhadap sejarah perkembangan perminyakan di Bumi Paguntaka sejak jaman Belanda hingga saat ini.\n\nSofian Raga juga mengungkapkan, bahwa kemajuan pesat Kota Tarakan seperti saat ini, tidak dapat dipisahkan dari sejarah perminyakan dunia. Dikarenakan migrasi para pekerja tambang dari luar Tarakan yang berbondong - bondong datang ke Tarakan, sehingga memperkaya keragaman etnis di Kota Tarakan, dan otomatis hal tersebut menjadi salah satu kekayaan ragam budaya.\n\nAdapun benda – benda/ property dari PT Pertamina yang akan disumbangkan antara lain alat – alat pengeboran yang pernah digunakan pada jaman Belanda, kemudian koleksi foto – foto dokumentasi proses pengeboran Belanda, dll. Sedangkan PT Medco Tarakan akan menyumbangkan maket perminyakan, rekonstruksi pembuatan minyak mentah sampai dengan pendistribusian ke masyarakat.\n\nOZ – DD – TiTiek – ARD, DKISP Kota Tarakan\n");
        jScrollPane2.setViewportView(jTextArea3);

        javax.swing.GroupLayout informasiLayout = new javax.swing.GroupLayout(informasi);
        informasi.setLayout(informasiLayout);
        informasiLayout.setHorizontalGroup(
            informasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(informasiLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        informasiLayout.setVerticalGroup(
            informasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtengah.add(informasi, "card4");

        tentang.setBackground(new java.awt.Color(0, 255, 204));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Tentang Kota Tarakan");

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(0, 255, 204));
        jTextArea4.setColumns(20);
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setText("Kota Tarakan adalah kota terbesar di Provinsi Kalimantan Utara,Indonesia dan juga merupakan kota terkaya ke-17 di Indonesia. Kota ini memiliki luas wilayah 250,80 km² dan sesuai dengan data Badan Kependudukan Catatan Sipil dan Keluarga Berencana, Kota Tarakan berpenduduk sebanyak 239.787 jiwa. Tarakan atau juga dikenal sebagai Bumi Paguntaka, berada pada sebuah pulau kecil. Semboyan dari kota Tarakan adalah Tarakan Kota \"BAIS\" (Bersih, Aman, Indah, Sehat dan Sejahtera).");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout tentangLayout = new javax.swing.GroupLayout(tentang);
        tentang.setLayout(tentangLayout);
        tentangLayout.setHorizontalGroup(
            tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentangLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel18)
                .addContainerGap(262, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        tentangLayout.setVerticalGroup(
            tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tentangLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE))
        );

        jtengah.add(tentang, "card5");

        wisata.setBackground(new java.awt.Color(153, 153, 153));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel11.setText("TUJUAN WISATA");

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\RizkyKiwa\\Documents\\NetBeansProjects\\VISUAL_B_1515015055_160497\\src\\PostTest3\\1.jpg")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Pantai Amal Tarakan");

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\RizkyKiwa\\Documents\\NetBeansProjects\\VISUAL_B_1515015055_160497\\src\\PostTest3\\4.JPG")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Grand Tarakan Mall");

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\RizkyKiwa\\Documents\\NetBeansProjects\\VISUAL_B_1515015055_160497\\src\\PostTest3\\mangrove-forest-tarakan.jpg")); // NOI18N

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Hutan Mangrove Tarakan");

        javax.swing.GroupLayout wisataLayout = new javax.swing.GroupLayout(wisata);
        wisata.setLayout(wisataLayout);
        wisataLayout.setHorizontalGroup(
            wisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wisataLayout.createSequentialGroup()
                .addGroup(wisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel9))
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel13))
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel14))
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel11))
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel12))
                    .addGroup(wisataLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        wisataLayout.setVerticalGroup(
            wisataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wisataLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtengah.add(wisata, "card6");

        getContentPane().add(jtengah, java.awt.BorderLayout.CENTER);

        jatas.setBackground(new java.awt.Color(204, 0, 0));
        jatas.setPreferredSize(new java.awt.Dimension(560, 160));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("KOTA TARAKAN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("SISTEM INFORMASI\n");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("DINAS KEBUDAYAAN DAN PARIWISATA\n");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("KALIMANTAN UTARA");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Visi dan Misi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setText("Informasi");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Tentang Kota");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Tujuan Wisata");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\RizkyKiwa\\Pictures\\cek1.png")); // NOI18N

        javax.swing.GroupLayout jatasLayout = new javax.swing.GroupLayout(jatas);
        jatas.setLayout(jatasLayout);
        jatasLayout.setHorizontalGroup(
            jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatasLayout.createSequentialGroup()
                .addGroup(jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jatasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(jatasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jatasLayout.setVerticalGroup(
            jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatasLayout.createSequentialGroup()
                .addGroup(jatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jatasLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(jatasLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        getContentPane().add(jatas, java.awt.BorderLayout.PAGE_START);

        jbawah.setBackground(new java.awt.Color(204, 0, 0));
        jbawah.setPreferredSize(new java.awt.Dimension(560, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Kemendikbudpar @2017");

        javax.swing.GroupLayout jbawahLayout = new javax.swing.GroupLayout(jbawah);
        jbawah.setLayout(jbawahLayout);
        jbawahLayout.setHorizontalGroup(
            jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawahLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel5)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jbawahLayout.setVerticalGroup(
            jbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jbawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jbawah, java.awt.BorderLayout.PAGE_END);

        jMenu4.setText("HOME");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Visi dan Misi");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Informasi");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Tentang Kota");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Tujuan Wisata");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("EXIT");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Exit Program");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(false);
        informasi.setVisible(true);
        tentang.setVisible(false);
        wisata.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        visimisi.setVisible(false);
        informasi.setVisible(false);
        tentang.setVisible(false);
        wisata.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(true);
        informasi.setVisible(false);
        tentang.setVisible(false);
        wisata.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(false);
        informasi.setVisible(true);
        tentang.setVisible(false);
        wisata.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(false);
        informasi.setVisible(false);
        tentang.setVisible(true);
        wisata.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(false);
        informasi.setVisible(false);
        tentang.setVisible(false);
        wisata.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(true);
        informasi.setVisible(false);
        tentang.setVisible(false);
        wisata.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(false);
        informasi.setVisible(false);
        tentang.setVisible(true);
        wisata.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        visimisi.setVisible(false);
        informasi.setVisible(false);
        tentang.setVisible(false);
        wisata.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel home;
    private javax.swing.JPanel informasi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel jatas;
    private javax.swing.JPanel jbawah;
    private javax.swing.JPanel jtengah;
    private javax.swing.JPanel tentang;
    private javax.swing.JPanel visimisi;
    private javax.swing.JPanel wisata;
    // End of variables declaration//GEN-END:variables
}
